/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;


import io.javalin.Javalin;
import kong.unirest.HttpResponse;
import kong.unirest.Unirest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;



import static org.junit.jupiter.api.Assertions.assertEquals;

class AppTest {

    private static Javalin app;
    private static String baseUrl;

    @BeforeAll
    public static void beforeAll() {
        app = App.getApp();
        app.start(0);
        int port = app.port();
        baseUrl = "http://localhost:" + port;
    }

    @AfterAll
    public static void afterAll() {
        app.stop();
    }
    @Test
    void testRoot() {
        HttpResponse<String> response = Unirest.get(baseUrl + "/").asString();
        String content = response.getBody();
        assertEquals(200, response.getStatus());
        assertEquals("Hello World", content);
    }
}
