/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;


import io.javalin.Javalin;
import kong.unirest.HttpResponse;
import kong.unirest.Unirest;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;


import java.io.IOException;
import java.sql.SQLException;

import static org.assertj.core.api.Assertions.assertThat;

class AppTest {

    private static Javalin app;
    private static String baseUrl;

    @BeforeAll
    public static void beforeAll() throws SQLException, IOException {
        app = App.getApp();
        app.start(0);
        int port = app.port();
        baseUrl = "http://localhost:" + port;
    }

    @AfterAll
    public static void afterAll() {
        app.stop();
    }
    @Test
    void rootTest() {
        HttpResponse<String> response = Unirest.get(baseUrl + "/").asString();

        assertThat(response.getStatus()).isEqualTo(200);
        assertThat(response.getBody()).contains("Анализатор страниц");
        assertThat(response.getBody()).contains("https://www.example.com");
    }

//    @Test
//    void urlsTest() {
//        HttpResponse<String> response = Unirest.get(baseUrl + "/urls").asString();
//
//        assertThat(response.getStatus()).isEqualTo(200);
//        assertThat(response.getBody()).contains("Сайты");
//    }
}
