/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexlet.code;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import gg.jte.ContentType;
import gg.jte.TemplateEngine;
import gg.jte.resolve.ResourceCodeResolver;
import hexlet.code.controller.RootController;
import hexlet.code.repository.BaseRepository;
import hexlet.code.util.NamedRoutes;
import io.javalin.Javalin;
import io.javalin.rendering.template.JavalinJte;

import java.io.File;
import java.net.URL;
import java.nio.file.Files;
import java.sql.Connection;
import java.sql.Statement;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {
        Javalin app = getApp();
        app.start(8080);
    }

    public static Javalin getApp() {
        HikariConfig hikariConfig = new HikariConfig();
        String jdbc = System.getenv("JDBC_DATABASE_URL");
        hikariConfig.setJdbcUrl(jdbc);

        try (HikariDataSource dataSource = new HikariDataSource(hikariConfig)) {
            URL url = App.class.getClassLoader().getResource("schema.sql");
            File file = new File(url.getFile());
            String sql = Files.lines(file.toPath())
                    .collect(Collectors.joining("\n"));
            Connection connection = dataSource.getConnection();
            Statement statement = connection.createStatement();
            statement.execute(sql);
            BaseRepository.dataSource = dataSource;
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }

        JavalinJte.init(createTemplateEngine());

        Javalin app = Javalin.create(config -> {
            config.plugins.enableDevLogging();
        });

        addRoutes(app);

        return app;
    }

    private static TemplateEngine createTemplateEngine() {
        ClassLoader classLoader = App.class.getClassLoader();
        ResourceCodeResolver codeResolver = new ResourceCodeResolver("templates", classLoader);
        return TemplateEngine.create(codeResolver, ContentType.Html);
    }

    private static void addRoutes(Javalin app) {
        app.get(NamedRoutes.rootPath(), RootController::getRootPage);
    }
}
