drop table if exists url_checks;
drop table if exists urls;

create table urls (
    id bigint generated by default as identity unique not null,
    name varchar(255),
    created_at timestamp not null,
    last_check timestamp
);

create table url_checks (
    id bigint generated by default as identity unique not null,
    url_id bigint not null,
    status_code smallint,
    h1 varchar(255),
    title  varchar(255),
    description text,
    created_at timestamp not null
);

alter table url_checks
add foreign key (url_id) references urls (id)
on delete cascade;
